<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml [
<!ELEMENT xml (Thread*)>
<!ATTLIST xml 
version CDATA #REQUIRED
>
<!ELEMENT Thread (RelQuestion, RelComment*)>
<!ATTLIST Thread
 THREAD_SEQUENCE CDATA #REQUIRED
>
<!ELEMENT RelQuestion (RelQSubject, RelQBody, RelQClean)>
<!ATTLIST RelQuestion
RELQ_ID CDATA #REQUIRED
RELQ_CATEGORY CDATA #REQUIRED
RELQ_DATE CDATA #REQUIRED
RELQ_USERID CDATA #REQUIRED
RELQ_USERNAME CDATA #REQUIRED
>
<!ELEMENT RelQSubject (#PCDATA)>
<!ELEMENT RelQBody (#PCDATA)>
<!ELEMENT RelQClean (#PCDATA)>
<!ELEMENT RelComment (RelCBody, RelCClean)>
<!ATTLIST RelComment
RELC_ID CDATA #REQUIRED
RELC_DATE CDATA #REQUIRED
RELC_USERID CDATA #REQUIRED
RELC_USERNAME CDATA #REQUIRED
RELC_RELEVANCE2RELQ CDATA #REQUIRED
>
<!ELEMENT RelCBody (#PCDATA)>
<!ELEMENT RelCClean (#PCDATA)>
]>
<xml version="1.0">

	<Thread THREAD_SEQUENCE="Q318_R6">
		<RelQuestion RELQ_ID="Q318_R6" RELQ_CATEGORY="Opportunities" RELQ_DATE="2012-12-26 17:50:49" RELQ_USERID="U3" RELQ_USERNAME="anonymous">
			<RelQSubject>IT Jobs in Qatar</RelQSubject>
			<RelQBody>how hard is it for you to get a decent paying job in qatar? I had applied in bayt,monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well, while its back to updating my CV, I'd love to hear about your experiences on getting a job here.</RelQBody>
			<RelQClean>IT Jobs in Qatar // how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here.</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R6_C1" RELC_DATE="2012-12-26 18:28:16" RELC_USERID="U5529" RELC_USERNAME="baazir" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Ive been here for a month and getting nothing back like u. Finished BSc IT and Worked in a large comp in UK for 3 years. Having hundred of knowledge sectors and certificates but everything became useless before gulf experience.

Beyond ad and job sites Im visiting to companies and created own portfolio web as well. Got 3 or 4 mails since advertised and just they got back my resume. Lets see

Good Luck to u :)</RelCBody>
			<RelCClean>Ive been here for a month and getting nothing back like u. Finished BSc IT and Worked in a large comp in UK for 3 years. Having hundred of knowledge sectors and certificates but everything became useless before gulf experience. Beyond ad and job sites Im visiting to companies and created own portfolio web as well. Got 3 or 4 mails since advertised and just they got back my resume. Lets see Good Luck to u :)</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C2" RELC_DATE="2012-12-26 19:56:40" RELC_USERID="U5530" RELC_USERNAME="lailuen" RELC_RELEVANCE2RELQ="?">
			<RelCBody>seems like there are lot of job opportunities but nobody seems to get it...


i hear people coming to work in Qatar everyday... but doesnt seems to be able to fing wokr myself</RelCBody>
			<RelCClean>seems like there are lot of job opportunities but nobody seems to get it... i hear people coming to work in Qatar everyday... but doesnt seems to be able to fing wokr myself</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C3" RELC_DATE="2012-12-26 22:03:05" RELC_USERID="U996" RELC_USERNAME="BlueBull" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Qatar is not the place for people with IT Experiencewho really want to make a career in IT. Qatar IT is desktop and network management only.</RelCBody>
			<RelCClean>Qatar is not the place for people with IT Experiencewho really want to make a career in IT. Qatar IT is desktop and network management only.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C4" RELC_DATE="2012-12-26 22:32:23" RELC_USERID="U5531" RELC_USERNAME="sandeepclt" RELC_RELEVANCE2RELQ="?">
			<RelCBody>i am here for last 1 month and not even called for a single interview. i have 8 yrs of IT exp and worked for one of the biggest MNC in India. looks like the decision to come here turning out to be wrong...

bcoz i am confident on my skills, may go back back to india after searching for 1 more month :)

i didn't get any guidance b4 coming. so pls come here if someone can get you a job...

Sandy</RelCBody>
			<RelCClean>i am here for last 1 month and not even called for a single interview. i have 8 yrs of IT exp and worked for one of the biggest MNC in India. looks like the decision to come here turning out to be wrong... bcoz i am confident on my skills; may go back back to india after searching for 1 more month :) i didn't get any guidance b4 coming. so pls come here if someone can get you a job... Sandy</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C5" RELC_DATE="2012-12-27 07:35:30" RELC_USERID="U5532" RELC_USERNAME="praveen06527" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Shall we talk about gulftalent...I think it is a wasiting of time...No positive response for me for the last three years from gulftalent.Now i stopped to login to that.better we go directly to the company career site.Expecting your valuable comments.thanks to all in advance.</RelCBody>
			<RelCClean>Shall we talk about gulftalent...I think it is a wasiting of time...No positive response for me for the last three years from gulftalent.Now i stopped to login to that.better we go directly to the company career site.Expecting your valuable comments.thanks to all in advance.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C6" RELC_DATE="2012-12-27 11:18:28" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="?">
			<RelCBody>how did u advertise your resume then? this place is kind of depressing isn't it?</RelCBody>
			<RelCClean>how did u advertise your resume then? this place is kind of depressing isn't it?</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C7" RELC_DATE="2012-12-27 12:53:02" RELC_USERID="U4100" RELC_USERNAME="Brad_cin_dell" RELC_RELEVANCE2RELQ="?">
			<RelCBody>On the same boat.. :-(</RelCBody>
			<RelCClean>On the same boat.. :-(</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C8" RELC_DATE="2012-12-27 15:04:25" RELC_USERID="U5533" RELC_USERNAME="shafcp" RELC_RELEVANCE2RELQ="?">
			<RelCBody>forward ur cv to admin@arablandgroup.com, let hope for the best</RelCBody>
			<RelCClean>forward ur cv to admin@arablandgroup.com; let hope for the best</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C9" RELC_DATE="2012-12-27 15:50:53" RELC_USERID="U5534" RELC_USERNAME="Ahmad_Mansoor" RELC_RELEVANCE2RELQ="?">
			<RelCBody>well maybe if there wasn't 1 billion of you guys trying to take the same job from those few companies. Yet the new generation is also going crazy enrolling in IT degrees... How many IT jobs you think there are in this place?

Unix and Linux are jobs for men in here.. Yes believe me, certain jobs are dedicated for each gender... an IT company that needs a Unix admin, that is 99.99% male dominated department would NEVER hire a woman.


Sorry to burst the bubble, reality is bitter


Good luck try harder.

</RelCBody>
			<RelCClean>well maybe if there wasn't 1 billion of you guys trying to take the same job from those few companies. Yet the new generation is also going crazy enrolling in IT degrees... How many IT jobs you think there are in this place? Unix and Linux are jobs for men in here.. Yes believe me; certain jobs are dedicated for each gender... an IT company that needs a Unix admin; that is 99.99% male dominated department would NEVER hire a woman. Sorry to burst the bubble; reality is bitter Good luck try harder.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C10" RELC_DATE="2012-12-27 16:16:18" RELC_USERID="U5535" RELC_USERNAME="Azhar89" RELC_RELEVANCE2RELQ="?">
			<RelCBody>An IT job in the middle east, especially Qatar - Not a smart idea!</RelCBody>
			<RelCClean>An IT job in the middle east; especially Qatar - Not a smart idea!</RelCClean>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q318_R52">
		<RelQuestion RELQ_ID="Q318_R52" RELQ_CATEGORY="Salary and Allowances" RELQ_DATE="2008-08-12 17:29:03" RELQ_USERID="U3" RELQ_USERNAME="anonymous">
			<RelQSubject>ONLINE JOBS</RelQSubject>
			<RelQBody>Recently I saw an ad by Google, data entry jobs online. It required we give a fee and then they promise us a fixed amount every month. Is this a scam? or is it ok to proceed with it?? If so, do anyone know sites to get more online jobs, which is safe?</RelQBody>
			<RelQClean>ONLINE JOBS // Recently I saw an ad by Google; data entry jobs online. It required we give a fee and then they promise us a fixed amount every month. Is this a scam? or is it ok to proceed with it?? If so; do anyone know sites to get more online jobs; which is safe?</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R52_C1" RELC_DATE="2008-08-12 17:36:04" RELC_USERID="U5536" RELC_USERNAME="classdiver" RELC_RELEVANCE2RELQ="?">
			<RelCBody>scam....takecare</RelCBody>
			<RelCClean>scam....takecare</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C2" RELC_DATE="2008-08-12 17:39:38" RELC_USERID="U63" RELC_USERNAME="mjamille28" RELC_RELEVANCE2RELQ="?">
			<RelCBody>well, probably is so i be more careful if i were you... why you looking for online jobs anyway,.. </RelCBody>
			<RelCClean>well; probably is so i be more careful if i were you... why you looking for online jobs anyway;..</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C3" RELC_DATE="2008-08-12 17:59:30" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Bcoz i got a baby and iam nt intrested to send him in a day care. thats y iam looking for an online job. so that i can work from home.</RelCBody>
			<RelCClean>Bcoz i got a baby and iam nt intrested to send him in a day care. thats y iam looking for an online job. so that i can work from home.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C4" RELC_DATE="2008-08-12 18:20:33" RELC_USERID="U1694" RELC_USERNAME="tallboy_v" RELC_RELEVANCE2RELQ="?">
			<RelCBody>I suggest u better start a baby sitting centre. You can earn good money by that way. Moreover ur baby will have other babies to play with. Me believes, couples who have got jobs as well as babies will benefit by this service of yours and you can make good money. Just my 2 cents.</RelCBody>
			<RelCClean>I suggest u better start a baby sitting centre. You can earn good money by that way. Moreover ur baby will have other babies to play with. Me believes; couples who have got jobs as well as babies will benefit by this service of yours and you can make good money. Just my 2 cents.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C5" RELC_DATE="2010-01-23 14:53:21" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="?">
			<RelCBody>i  am looking for


 job networking
Vendor Certifications:

?	Microsoft Certified System Administrator (MCSA) (ID # 6193829)
?	Cisco Certified Network Associate (CCNA) (ID#11688483 ) (Exam code: 640-802)
Academic Qualifications:-

ng (009746235545 )
</RelCBody>
			<RelCClean>i am looking for job networking Vendor Certifications:  Microsoft Certified System Administrator (MCSA) (ID # 6193829)  Cisco Certified Network Associate (CCNA) (ID#11688483 ) (Exam code: 640-802) Academic Qualifications:- ng (009746235545 )</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C6" RELC_DATE="2010-03-05 10:41:59" RELC_USERID="U5537" RELC_USERNAME="remyajay" RELC_RELEVANCE2RELQ="?">
			<RelCBody>I am a Diploma holder in Electronics Engineering..  Now i have a baby, so i am searching online jobs. Please contact to 6144520.</RelCBody>
			<RelCClean>I am a Diploma holder in Electronics Engineering.. Now i have a baby; so i am searching online jobs. Please contact to 6144520.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C7" RELC_DATE="2010-03-05 13:06:46" RELC_USERID="U5538" RELC_USERNAME="Aussie235" RELC_RELEVANCE2RELQ="?">
			<RelCBody>I think it is a scam.

Do not pay any fee, false promises are made online everyday.
Be carefull.</RelCBody>
			<RelCClean>I think it is a scam. Do not pay any fee; false promises are made online everyday. Be carefull.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C8" RELC_DATE="2010-03-05 13:10:57" RELC_USERID="U1070" RELC_USERNAME="fanonite" RELC_RELEVANCE2RELQ="?">
			<RelCBody>online jobs are 99.9% scam....</RelCBody>
			<RelCClean>online jobs are 99.9% scam....</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C9" RELC_DATE="2010-03-05 13:28:14" RELC_USERID="U3920" RELC_USERNAME="HABIBMDH" RELC_RELEVANCE2RELQ="?">
			<RelCBody>SCAM !!!!!!!!!!!!!!!!</RelCBody>
			<RelCClean>SCAM !!!!!!!!!!!!!!!!</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q318_R52_C10" RELC_DATE="2010-04-04 07:31:18" RELC_USERID="U5539" RELC_USERNAME="Rockistan" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Can anybody help me out in finding out an online data entry job or an Online form submission jobs in QATAR ???IS THERE ANY COMPANY ANY FIRM WHICH PROVIDE THESE KINDA JOBS ??? ONLINE DATA ENTRY KINDA JOBS??? PLZ I NEED THIS JOB URGENTLY AS POSSIBLE WAITING 4 UR REPLY !PLZ DO REPLY TO THIS THREAD AS SOON AS POSSIBLE THANKS :) actually I wanted to knw abt the websites which provide this kinds jobs but the payment should be good enough depending upon work load? secondy i searched randomly in google but most of them r jst fake as far as em concerned!! but surely i`ll chk out in classifieds here in qatar living! frankly speakin i actually wanted da online form submisson job in QATAR only dats the imp. part! plz help me out if and post a link if anyone knws abt any website or if any one is doin dis kinda job?</RelCBody>
			<RelCClean>Can anybody help me out in finding out an online data entry job or an Online form submission jobs in QATAR ???IS THERE ANY COMPANY ANY FIRM WHICH PROVIDE THESE KINDA JOBS ??? ONLINE DATA ENTRY KINDA JOBS??? PLZ I NEED THIS JOB URGENTLY AS POSSIBLE WAITING 4 UR REPLY !PLZ DO REPLY TO THIS THREAD AS SOON AS POSSIBLE THANKS :) actually I wanted to knw abt the websites which provide this kinds jobs but the payment should be good enough depending upon work load? secondy i searched randomly in google but most of them r jst fake as far as em concerned!! but surely i`ll chk out in classifieds here in qatar living! frankly speakin i actually wanted da online form submisson job in QATAR only dats the imp. part! plz help me out if and post a link if anyone knws abt any website or if any one is doin dis kinda job?</RelCClean>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q319_R1">
		<RelQuestion RELQ_ID="Q319_R1" RELQ_CATEGORY="Politics" RELQ_DATE="2008-05-07 13:27:45" RELQ_USERID="U2724" RELQ_USERNAME="mghozlan">
			<RelQSubject>Mix Marriages</RelQSubject>
			<RelQBody>&amp;lt;p&amp;gt;
Do u think that 2 from 2 different cultures shall have a good marriage i mean will it last, (believes, customs, even language) not the same !

&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
i'm not talking about 2 from 2 different countries in?Europe, or 2 in Asia, or 2 in?Africa, ... i'm talking about the one's where completely no similarity?

&amp;lt;/p&amp;gt;
</RelQBody>
			<RelQClean>Mix Marriages // Do u think that 2 from 2 different cultures shall have a good marriage i mean will it last; (believes; customs; even language) not the same ! i'm not talking about 2 from 2 different countries in Europe; or 2 in Asia; or 2 in Africa; ... i'm talking about the one's where completely no similarity?</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q319_R1_C1" RELC_DATE="2008-05-07 13:29:38" RELC_USERID="U1724" RELC_USERNAME="Gumby" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Certainly it can work, and work well, depends on the individuals.
</RelCBody>
			<RelCClean>Certainly it can work; and work well; depends on the individuals.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C2" RELC_DATE="2008-05-07 13:32:55" RELC_USERID="U78" RELC_USERNAME="qatarisun" RELC_RELEVANCE2RELQ="?">
			<RelCBody>&amp;lt;p style=&amp;quot;margin: 0in 0in 10pt&amp;quot; class=&amp;quot;MsoNormal&amp;quot;&amp;gt;
&amp;lt;span style=&amp;quot;font-size: 9pt; color: #454545; line-height: 115%; font-family: 'Verdana','sans-serif'&amp;quot;&amp;gt;but if they both will try to work it out, and both will adjust themselves? through the years of togetherness.... everything is possible.. why not? I know few examples when she is European/Canadian/Eastern European, and he is Jamaica/Lebanese/Mexican? or she is Brazilian, he is English?why not??&amp;lt;/span&amp;gt;
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
********** [img_assist|nid=102563|title=QS|desc=|link=none|align=left|width=|height=0] &amp;lt;strong&amp;gt;Copyright?Mr.PAUL &amp;lt;/strong&amp;gt;
&amp;lt;/p&amp;gt;
</RelCBody>
			<RelCClean>but if they both will try to work it out; and both will adjust themselves  through the years of togetherness.... everything is possible.. why not? I know few examples when she is European/Canadian/Eastern European; and he is Jamaica/Lebanese/Mexican… or she is Brazilian; he is English…why not?? ********** [img_assist|nid=102563|title=QS|desc=|link=none|align=left|width=|height=0] Copyright©Mr.PAUL</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C3" RELC_DATE="2008-05-07 13:35:01" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="?">
			<RelCBody>&amp;lt;p&amp;gt;
&amp;amp;#160;
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
&amp;amp;#160;
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
It can work of course an it does work see many of the mixed marriages around the world. People learn to compromise and to adjust if they are clever.
&amp;lt;/p&amp;gt;
</RelCBody>
			<RelCClean>It can work of course an it does work see many of the mixed marriages around the world. People learn to compromise and to adjust if they are clever.</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C4" RELC_DATE="2008-05-07 13:37:26" RELC_USERID="U463" RELC_USERNAME="swissgirl39" RELC_RELEVANCE2RELQ="?">
			<RelCBody>&amp;lt;p&amp;gt;
love negoates all barriers
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
&amp;amp;#160;
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
&amp;amp;#160;
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
&amp;lt;font color=&amp;quot;#000000&amp;quot;&amp;gt;*WHAT WOULD YOU DO IF YOU KNEW YOU COULD NOT FAIL?*&amp;lt;/font&amp;gt;

&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
&amp;lt;a href=&amp;quot;http://www.myswitzerland.com/en.cfm/home&amp;quot;&amp;gt;http://www.myswitzerland.com/en.cfm/home&amp;lt;/a&amp;gt;

&amp;lt;/p&amp;gt;
</RelCBody>
			<RelCClean>love negoates all barriers *WHAT WOULD YOU DO IF YOU KNEW YOU COULD NOT FAIL?* http://www.myswitzerland.com/en.cfm/home</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C5" RELC_DATE="2008-05-07 13:44:19" RELC_USERID="U78" RELC_USERNAME="qatarisun" RELC_RELEVANCE2RELQ="?">
			<RelCBody>&amp;lt;p&amp;gt;
love has nothing to do with that...if they NEED each other, they will work it out..

&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
if not.. forget about it....no any &amp;amp;quot;love&amp;amp;quot; can help....
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
********** [img_assist|nid=102563|title=QS|desc=|link=none|align=left|width=|height=0] &amp;lt;strong&amp;gt;Copyright?Mr.PAUL &amp;lt;/strong&amp;gt;
&amp;lt;/p&amp;gt;
</RelCBody>
			<RelCClean>"love has nothing to do with that...if they NEED each other; they will work it out.. if not.. forget about it....no any ""love"" can help.... ********** [img_assist|nid=102563|title=QS|desc=|link=none|align=left|width=|height=0] Copyright©Mr.PAUL"</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C6" RELC_DATE="2008-05-07 13:46:17" RELC_USERID="U5540" RELC_USERNAME="NAVYBLUE" RELC_RELEVANCE2RELQ="?">
			<RelCBody>?f they love each other too much that can make th?ngs and d?fferences work together...love and respct is the secret
</RelCBody>
			<RelCClean>ıf they love each other too much that can make thıngs and dıfferences work together...love and respct is the secret</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C7" RELC_DATE="2008-05-07 13:49:27" RELC_USERID="U16" RELC_USERNAME="Oryx" RELC_RELEVANCE2RELQ="?">
			<RelCBody>&amp;lt;p&amp;gt;
I can't get the lock fixed on the boot of my car for love nor money!

&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
For the love of whoever fix yourself please boot lock!
&amp;lt;/p&amp;gt;
</RelCBody>
			<RelCClean>I can't get the lock fixed on the boot of my car for love nor money! For the love of whoever fix yourself please boot lock!</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C8" RELC_DATE="2008-05-07 13:52:54" RELC_USERID="U78" RELC_USERNAME="qatarisun" RELC_RELEVANCE2RELQ="?">
			<RelCBody>we have got a shortage yesterday... hey someone from KAHRAMAA with BIG... LOVE.. can you pls fix it???
**********
[img_assist|nid=102563|title=QS|desc=|link=none|align=left|width=|height=0]
&amp;lt;b&amp;gt;Copyright?Mr.PAUL &amp;lt;/b&amp;gt;


</RelCBody>
			<RelCClean>we have got a shortage yesterday... hey someone from KAHRAMAA with BIG... LOVE.. can you pls fix it??? ********** [img_assist|nid=102563|title=QS|desc=|link=none|align=left|width=|height=0] Copyright©Mr.PAUL</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C9" RELC_DATE="2008-05-07 13:54:49" RELC_USERID="U385" RELC_USERNAME="owen" RELC_RELEVANCE2RELQ="?">
			<RelCBody>&amp;lt;p&amp;gt;
there are a lot living testimonies that this?kind of relationship works...
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
&amp;amp;#160;
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
you got to work harder in order to make?a relationship work, and this goes to?all sort of?&amp;amp;quot;mixes&amp;amp;quot;?&amp;amp;quot;combination&amp;amp;quot;?of?nationalities you got in mind.. Love conquers all as they say.. &amp;lt;img src=&amp;quot;/sites/all/modules/tinymce/tinymce/jscripts/tiny_mce/plugins/emotions/images/smiley-smile.gif&amp;quot; border=&amp;quot;0&amp;quot; alt=&amp;quot;Smile&amp;quot; title=&amp;quot;Smile&amp;quot; /&amp;gt;?
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
[img_assist|nid=12867|link=none|align=left|width=|height=0]&amp;lt;strong&amp;gt;Nothing in life is to be feared. It is only to be understood.&amp;lt;/strong&amp;gt;

&amp;lt;/p&amp;gt;
</RelCBody>
			<RelCClean>"there are a lot living testimonies that this kind of relationship works... you got to work harder in order to make a relationship work; and this goes to all sort of ""mixes"" ""combination"" of nationalities you got in mind.. Love conquers all as they say..   [img_assist|nid=12867|link=none|align=left|width=|height=0] Nothing in life is to be feared. It is only to be understood."</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R1_C10" RELC_DATE="2008-05-07 13:55:58" RELC_USERID="U18" RELC_USERNAME="Khanan" RELC_RELEVANCE2RELQ="?">
			<RelCBody>&amp;lt;p&amp;gt;
early morning i got call from the buddy with regard to that...
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
was surprized to hear that....
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
i think some inspecotrs came to the house.....
&amp;lt;/p&amp;gt;
&amp;lt;p&amp;gt;
&amp;amp;#160;
&amp;lt;/p&amp;gt;
</RelCBody>
			<RelCClean>early morning i got call from the buddy with regard to that... was surprized to hear that.... i think some inspecotrs came to the house.....</RelCClean>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q319_R2">
		<RelQuestion RELQ_ID="Q319_R2" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2012-12-19 20:28:26" RELQ_USERID="U5541" RELQ_USERNAME="JomanaZ">
			<RelQSubject>Mixed Marriages </RelQSubject>
			<RelQBody>With the world turning into a small village, mixed marriages have become more and more common.


If you are in a mixed marriage relationship and living in Doha, Could you provide details on how you and your significant other met? where? how long have you been married for? and what are the goods and bads in a mixed marriage?

Thank you,</RelQBody>
			<RelQClean>Mixed Marriages // With the world turning into a small village; mixed marriages have become more and more common. If you are in a mixed marriage relationship and living in Doha; Could you provide details on how you and your significant other met? where? how long have you been married for? and what are the goods and bads in a mixed marriage? Thank you;</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q319_R2_C1" RELC_DATE="2012-12-19 20:55:39" RELC_USERID="U999" RELC_USERNAME="LOL.XD" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Dont Try Dude i m Regreting :D Dont Marry at all Thats The Best i cant Tell You!</RelCBody>
			<RelCClean>Dont Try Dude i m Regreting :D Dont Marry at all Thats The Best i cant Tell You!</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C2" RELC_DATE="2012-12-19 21:14:06" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Met in a bar, must say I was very drunk</RelCBody>
			<RelCClean>Met in a bar; must say I was very drunk</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C3" RELC_DATE="2012-12-19 21:33:34" RELC_USERID="U5127" RELC_USERNAME="dash201" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Well she was working as waitress at a cocktail bar...</RelCBody>
			<RelCClean>Well she was working as waitress at a cocktail bar...</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C4" RELC_DATE="2012-12-19 22:14:23" RELC_USERID="U269" RELC_USERNAME="britexpat" RELC_RELEVANCE2RELQ="?">
			<RelCBody>What a strange question.


Mixed marriages can succeed but they take a lot of effort from both parties.

Good luck with yours..</RelCBody>
			<RelCClean>What a strange question. Mixed marriages can succeed but they take a lot of effort from both parties. Good luck with yours..</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C5" RELC_DATE="2012-12-19 23:18:57" RELC_USERID="U969" RELC_USERNAME="one_shot" RELC_RELEVANCE2RELQ="?">
			<RelCBody>well said Brit
nothing to add more.

in fact i think u stole my comment :) grrrrr</RelCBody>
			<RelCClean>well said Brit nothing to add more. in fact i think u stole my comment :) grrrrr</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C6" RELC_DATE="2012-12-19 23:34:11" RELC_USERID="U2484" RELC_USERNAME="Blosted" RELC_RELEVANCE2RELQ="?">
			<RelCBody>@costylove what the hell? </RelCBody>
			<RelCClean>@costylove what the hell?</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C7" RELC_DATE="2012-12-19 23:35:51" RELC_USERID="U5542" RELC_USERNAME="costylove" RELC_RELEVANCE2RELQ="?">
			<RelCBody>i said it ! :P</RelCBody>
			<RelCClean>i said it ! :P</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C8" RELC_DATE="2012-12-19 23:37:59" RELC_USERID="U2484" RELC_USERNAME="Blosted" RELC_RELEVANCE2RELQ="?">
			<RelCBody>congratulations!</RelCBody>
			<RelCClean>congratulations!</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C9" RELC_DATE="2012-12-20 00:09:51" RELC_USERID="U5543" RELC_USERNAME="arc736" RELC_RELEVANCE2RELQ="?">
			<RelCBody>Dear,
there is no specific Formula for a successful Marriage whether its, Loved, Arranged, Mixed, Intercontinental its all depends on ones attitude n sacrifices...

Choose your way wiseLy
gOOd lucK
;)</RelCBody>
			<RelCClean>Dear; there is no specific Formula for a successful Marriage whether its; Loved; Arranged; Mixed; Intercontinental its all depends on ones attitude n sacrifices... Choose your way wiseLy gOOd lucK ;)</RelCClean>
		</RelComment>

		<RelComment RELC_ID="Q319_R2_C10" RELC_DATE="2013-05-03 14:55:50" RELC_USERID="U5542" RELC_USERNAME="costylove" RELC_RELEVANCE2RELQ="?">
			<RelCBody>...</RelCBody>
			<RelCClean>...</RelCClean>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q319_R6">
		<RelQuestion RELQ_ID="Q319_R6" RELQ_CATEGORY="Qatari Culture" RELQ_DATE="2009-10-21 12:12:02" RELQ_USERID="U5544" RELQ_USERNAME="pigrah">
			<RelQSubject>interacial relationship</RelQSubject>
			<RelQBody>OK so we see a lot of interacial relationships in this country..what do u guys think about it?


common...i need ur opinon.</RelQBody>
			<RelQClean>interacial relationship // OK so we see a lot of interacial relationships in this country..what do u guys think about it? common...i need ur opinon.</RelQClean>
		</RelQuestion>

		<RelComment RELC_ID="Q319_R6_C1" RELC_DATE="2009-10-21 12:14:02" RELC_USERID="U63" RELC_USERNAME="mjamille28" RELC_RELEVANCE2RELQ="?">
			<RelCBody>it happens, no big deal although some people seem to get the kick out of making it a big deal... it's their choice and nobody's business but theirs and theirs alone..
&amp;lt;a target=&amp;quot;_blank&amp;quot; href=&amp;quot;http://www.blingcheese.com/&amp;quot;&amp;gt;&amp;lt;img src=&amp;quot;http://i153.photobucket.com/albums/s235/revmyspace2/graphics/Misc/Smileys/smiley_25009t7y685v0e.gif&amp;quot; title=&amp;quot;MySpace Comments&amp;quot; border=&amp;quot;0&amp;quot;&amp;gt;&amp;lt;/a&amp;gt;&amp;lt;br&amp;gt;&amp;lt;a target=&amp;quot;_blank&amp;quot; href=&amp;quot;http://www.blingchees</RelCBody>
			<RelCClean>it happens; no big deal although some people seem to get the kick out of making it a big deal... it's their choice and nobody's business but theirs and theirs alone..</RelCClean>
		</RelComment>
